/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_LAPU_LAPU_TECHS'		),
		('LEADER_CVS_LAPU_LAPU_CIVICS'		),
		('LEADER_CVS_LAPU_LAPU_DISTRICTS'	),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS'	),
		('LEADER_CVS_LAPU_LAPU_PROJECTS'	),
		('LEADER_CVS_LAPU_LAPU_DIPLOMACY'	),
		('LEADER_CVS_LAPU_LAPU_UNITS'		),
		('LEADER_CVS_LAPU_LAPU_TACTICS'		),
		('LEADER_CVS_LAPU_LAPU_EXPANSION'	),
		('LEADER_CVS_LAPU_LAPU_PSUEDOS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,				System				)
VALUES  ('LEADER_CVS_LAPU_LAPU_TECHS',		'AGENDA_CVS_LAPU_LAPU',	'Technologies'		),
		('LEADER_CVS_LAPU_LAPU_CIVICS',		'AGENDA_CVS_LAPU_LAPU',	'Civics'			),
		('LEADER_CVS_LAPU_LAPU_DISTRICTS',	'AGENDA_CVS_LAPU_LAPU',	'Districts'			),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'AGENDA_CVS_LAPU_LAPU',	'Buildings'			),
		('LEADER_CVS_LAPU_LAPU_PROJECTS',	'AGENDA_CVS_LAPU_LAPU',	'Projects'			),
		('LEADER_CVS_LAPU_LAPU_UNITS',		'AGENDA_CVS_LAPU_LAPU',	'Units'				),
		('LEADER_CVS_LAPU_LAPU_TACTICS',	'AGENDA_CVS_LAPU_LAPU',	'Tactics'			),
		('LEADER_CVS_LAPU_LAPU_DIPLOMACY',	'AGENDA_CVS_LAPU_LAPU',	'DiplomaticActions'	),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'AGENDA_CVS_LAPU_LAPU',	'PlotEvaluations'	),
		('LEADER_CVS_LAPU_LAPU_PSUEDOS',	'AGENDA_CVS_LAPU_LAPU',	'PsuedoYields'		);

-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_SHIPBUILDING',					1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_CELESTIAL_NAVIGATION',			1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_CARTOGRAPHY',						1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_SQUARE_RIGGING',					1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_ECONOMICS',						1		),
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_BRONZE_WORKING',					1		), -- LEADER SPECIFIC
		('LEADER_CVS_LAPU_LAPU_TECHS',		'TECH_IRON_WORKING',					1		), -- LEADER SPECIFIC
		-- CIVICS
		('LEADER_CVS_LAPU_LAPU_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_LAPU_LAPU_CIVICS',		'CIVIC_EXPLORATION',					1		),
		-- DISTRICTS
		('LEADER_CVS_LAPU_LAPU_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_LAPU_LAPU_DISTRICTS',	'DISTRICT_HARBOR',						1		),
		('LEADER_CVS_LAPU_LAPU_DISTRICTS',	'DISTRICT_ENCAMPMENT',					1		), -- LEADER SPECIFIC
		-- BUILDINGS
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_CVS_PHILIPPINES_UI',			1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_LIGHTHOUSE',					1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_SHIPYARD',					1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_SEAPORT',						1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_BARRACKS',					1		), -- LEADER SPECIFIC
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_ARMORY',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_MILITARY_ACADEMY',			1		), -- LEADER SPECIFIC
		-- WONDERS
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_EIFFEL_TOWER',				1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_GREAT_LIGHTHOUSE',			1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_VENETIAN_ARSENAL',			1		),
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_ALHAMBRA',					1		), -- LEADER SPECIFIC
		('LEADER_CVS_LAPU_LAPU_BUILDINGS',	'BUILDING_TERRACOTTA_ARMY',				1		), -- LEADER SPECIFIC
		-- PROJECTS
		-- UNITS
		('LEADER_CVS_LAPU_LAPU_UNITS',		'UNIT_CVS_PHILIPPINES_UU',				1		),
		('LEADER_CVS_LAPU_LAPU_UNITS',		'UNIT_CVS_LAPU_LAPU_UU',				1		), -- LEADER SPECIFIC
		-- TACTICS
		-- DIPLOMACY
		('LEADER_CVS_LAPU_LAPU_DIPLOMACY',	'DIPLOACTION_PROPOSE_TRADE',			1		);

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'Coastal',								1,			15,		NULL					),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'Resource Class',						1,			5,		'RESOURCECLASS_BONUS'	),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'Resource Class',						1,			5,		'RESOURCECLASS_LUXURY'	),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'New Resources',						1,			15,		NULL					),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'Specific Feature',						1,			5,		'FEATURE_CLIFFS_DOVER'	),
		('LEADER_CVS_LAPU_LAPU_EXPANSION',	'Specific Feature',						1,			5,		'FEATURE_PIOPIOTAHI'	),
		-- PSUEDOS
		('LEADER_CVS_LAPU_LAPU_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',				1,			5,		NULL					),
		('LEADER_CVS_LAPU_LAPU_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',				1,			50,		NULL					),
		('LEADER_CVS_LAPU_LAPU_PSUEDOS',	'PSEUDOYIELD_GPP_ADMIRAL',				1,			30,		NULL					),
		('LEADER_CVS_LAPU_LAPU_PSUEDOS',	'PSEUDOYIELD_UNIT_NAVAL_COMBAT',		1,			30,		NULL					);